spring:
  config:
    import: "optional:file:../../.env[.properties]"

  profiles:
    active: separate

  datasource:
    url: jdbc:postgresql://${NETWORKING_POSTGRES_DB_HOST}:${NETWORKING_POSTGRES_DB_INTERNAL_PORT}/${NETWORKING_POSTGRES_DB_NAME}
    username: ${NETWORKING_POSTGRES_DB_USER}
    password: ${NETWORKING_POSTGRES_DB_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:session-schema.sql

  session:
    store-type: jdbc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - debug