spring:
  datasource:
#    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_INTERNAL_PORT}/${POSTGRES_DB}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}

    url: jdbc:postgresql://localhost:5432/my-app-db
    username: postgres
    password: 267115

  sql:
    init:
      mode: always
      schema-locations: classpath:session-schema.sql

  session:
    store-type: jdbc

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: networking

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - debug
          - env

server:
  port: 8081

grpc:
  server:
    port: 9092